### PR TITLE
Add feature: multiple sheets

### PR DESCRIPTION
**Pull request by cesasol**
Add the option to have more than one sheet per doc

### CODE REVIEW

**Comment by mckennapsean** [comment]
This is an interesting PR!

I hadn't thought about using multiple sheets before, but you totally could. I can think of some use-cases where this could be really helpful, and you could even have multiple forms being used on a single script just by changing a value. Very nice idea!

My only concern is that this seems a little advanced. We want the tutorial example to contain the simplest working solution, and adding something like this is another step that someone could accidentally mess up. There are some other interesting questions here, like what if someone tries to access a sheet that doesn't exist yet? Is it added dynamically or does it just fail silently? We have another issue about dynamically adding columns to the spreadsheet which to me seems related to this idea of using more than one spreadsheet. You could really have a customizable (but potentially less "secure") form and set of data that user's could supply.

That being said, it would not be difficult to have the custom form-field in the server-side code. I just think it may not be needed in the client-side code in the tutorial, but the tutorial could mention it towards the bottom as a piece of advanced functionality. Also, because this is a "magic" value, I would argue that the hidden field's name should be something more specific like `googleSheetName`. Otherwise, I don't see an issue pulling in this new functionality! Others' thoughts?

**Comment by cesasol** [comment]
If the specifyed sheet does not exist, and does neither the `responses` sheet, it silently fails, this behavior is the current if there is no sheet named `responses`. To solve this particular issue maybe we can add:
```javascript
if (sheet != null) {
  throw "Sheet  " + whichSheet + "does not exist!";
}
```
And changing the value to `googleSheetName` is a great idea. Surely by the time you see this it would be commited to the PR

**Comment by mckennapsean** [comment]
Hmmm, the discussion in #18 made me think. Adding a hidden input element is still not the most clear way to do something like this. What if instead we store this data as part a declaration for the form with a `data-` attribute instead? This would be more robust and less likely to break existing implementations as well (in case someone used a hidden input field of the same name).

This would require some client-side Javascript to parse the `data-` attribute, if it exists, otherwise fill in with the default ("responses"), and the server-side / Google Script would need access to this data still. But thanks for bringing this idea to our attention! If you want to make these changes, I think that is a more reasonable solution and in-line with other similar changes we can make to the form down the line. Thanks!

**Comment by mckennapsean** [comment]
See #93 - one of the suggested changes made me think that we could use `data-` attributes for customizing the form functionality (e.g. checking for email, showing success/thank-you divs, which sheet to save to, etc.). What do you think about that? This would require some significant changes to support everything, but all of these pull requests have sparked these wonderful ideas, so thank you for sharing your contributions with us! Keeping this open while I reflect and wait to hear from others, but not opposed to other pull requests if you know what I am chattering about!

**Comment by mckennapsean** [comment]
FYI, I have pulled this idea into another PR. Only thing missing from that implementation is a way to improve error messages if the sheet doesn't exist. Thanks for the idea, you have sparked some great improvements, and feel free to send a PR on the error message improvements. :)

**Pull request closed without merging**
