### PR TITLE
Better email formatting

### PR DESCRIPTION
**Pull request by martynhoyer**
As discussed in https://github.com/dwyl/html-form-send-email-via-google-script-without-server/issues/41#issuecomment-273320755

Updates to sample script and readme to show how to improve formatting of the email sent.

### CODE REVIEW

**Comment by mckennapsean** [comment]
Good job, @martynhoyer ! Nicely written description of how to add on prettier emails to the script. I only have a few minor corrections and tweaks that I could suggest to improve how this fits with the page.

One downside is the `reply-to` requiring an email to be set, in case there is an error with the input email or there isn't one. I know this is about sending emails, but this tutorial can work for any kind of form, which I have personally used for running several anonymous web tests and surveys. This could be stated with a caveat, and that someone can remove this line from their script as needed. I usually tweaked the script a bit before, so maybe this is reasonable to do so.

I would suggest that someone else test this first before pulling it in. I wish we had some somewhat-automated testing too... deserving of a new issue granted. Does anyone else want to review this or what they suggest to handle the PR?

If it all works OK, should we just pull in the PR and make the corrections after? Or suggest changes here to make before accepting? Does it matter where the images are stored for the main repository?

Thanks again!

**Comment by martynhoyer** [comment]
Fair point on the `replyTo`, yeah, I put that in for my own use case, but it should be flagged as optional (it could potentially check for existence of the field too).

As you mentioned in https://github.com/dwyl/html-form-send-email-via-google-script-without-server/issues/75 it might be worth having a think about spam at this point, and take the fields from the spreadsheet, rather than directly from the `POST`ed data.

**Comment by iteles** [comment]
@martynhoyer @mckennapsean I would suggest that we open a separate issue on this for now (agree `reply-to` should be optional!) and add a line into the readme to reflect the temporary status with a reference to the relevant issue.

If you have time to take this on @martynhoyer, it would be much appreciated :tada:

**Comment by martynhoyer** [comment]
Can do!

**Comment by martynhoyer** [comment]
Updated! 
Tweaks/amends gladly accepted. As well as some testing as @mckennapsean suggested!

In terms of images, I couldn't really figure out the best thing to do with images in the readme, since pasting them in from the clipboard in the web-based readme editor wasn't doing anything, so I just threw one into a comment which I never posted and used its URL. Feel free to move or reproduce it.

**Comment by iteles** [comment]
@martynhoyer That's exactly how I deal with images too! 👍

**Comment by mckennapsean** [comment]
That is good to know on the images! I was wondering if they were stored in a forked repository which could be deleted by someone (and would images be too?). But I am guessing that this would not. I will review the content now!

**Comment by mckennapsean** [comment]
Lastly, for the Google Script on the hosted spreadsheet, it looks like @nelsonic is the owner. If this gets accepted (and for future changes) should we just ping you for adding in the updated code to the spreadsheet's script editor? The current version on the spreadsheet is actually out-of-date with the repository too, which could be problematic for folks copying the form and using the code there rather than what is in the repository! Thanks :)

**Comment by martynhoyer** [comment]
I'll review the comments in depth a bit later on, but just on this one:

> Lastly, a question, the output in the email seems not to match the order of the form data (or spreadsheet obviously). Do you know how to make a quick modification to improve this? If not, I can file another issue on this for the future, as it is a nice feature to add, but by no means required for this pull request.

I did notice that myself, but couldn't get it playing nicely whatever I did. I made the assumption that's it's something to do with the master sheet that I've copied from and that maybe the columns/rows have some sort of hidden ID on them that they're being ordered by? That's a bit of a guess and doesn't really make much sense (especially since the email part of the script doesn't actually touch the spreadsheet data), but I tried reordering form elements and reordering the spreadsheet columns and nothing changed (they remain in the order that the original spreadsheet was in).

As I mentioned in the other comment when we were discussing spam concerns, I'd quite like to see it use the form data to populate the spreadsheet, then use the spreadsheet data to send the email, which could potentially eliminate this ordering problem too.

**Comment by mckennapsean** [comment]
Okay, sounds good @martynhoyer - thanks for the exploration! I will post another issue about it. I think it is based on how the data is scraped and sent via Javascript/AJAX, and it is an object/dictionary, so there may be some complexity to preserving order. The spreadsheet just checks if a column header exists then adds the data, so the order wouldn't matter in that case (or you could use the header as a key into the e.parameters array, not sure which we do offhand).

**Comment by martynhoyer** [comment]
> Just a few minor points for cleaning up the code. For the code (google-apps-script.js), Line 15 could use a semicolon, and the function following (formatMailBody()) is likely best put into the global scope of the entire Google Script, as that is usually what Javascript does on its own. Let me know if that is unclear. For that same function, is there a reason you need to call obj.hasOwnProperty()? I didn't test without, but I was wondering if that is truly needed or if maybe some weird null values were getting passed through by Javascript. I would also recommend adding a brief comment above the function after you move it to explain what it does, but otherwise the code looks great! 

Cool, thanks for the pointers. I've made those changes.  
Regarding the `hasOwnProperty` call, I'll be honest, it was just a copy/paste after Googling, but it was about not looping inherited properties. It works ok without it though, so I've removed it.

> I like your write-up / Step 13 added to the README, but I am worried it is a bit long.

Yep, having thought about it, I don't think any of it is needed if we're simply providing the code, and, more importantly, updating the master doc with the updated script. The docs were originally a here's-how-to-do-it-yourself kind of walkthrough, but if we're giving them the code, then all we need to explain is how to adjust the HTML if they don't like my defaults I think? 

I've amended the readme along those lines, so would appreciate another look!

**Comment by mckennapsean** [comment]
Looks good! By the way, functions can go anywhere, before or after they are used, as they get hoisted to the top. Oh, Javascript. :)

I think you brought up a valid point, to not show the code in place since it should be in the original spreadsheet. But we need to address this issue of live-updating the Google Spreadsheet.

I could make a copy of the current spreadsheet on Google Drive, add a few collaborators who can edit it, and update the link in the main repo so people get the up-to-date code. Once this is something we can update, we can pull this in!

**Comment by mckennapsean** [comment]
@iteles & @nelsonic - the code is set to be merged, but I am unable to update the Google Spreadsheet/Script which is required by this PR.

I am suggesting a few options, feel free to pick one or suggest another! :)

1. Add the modified Google Javascript code to the spreadsheet's script editor & save a new version.
2. Grant write access to a collaborator for one of us to add the code to the spreadsheet (my sn: mckennapsean@gmail.com).
3. I could create a new spreadsheet file, add some collaborators for editing it, and update the repository in a new PR for this new "version" / link.

Thanks!

**Comment by nelsonic** [comment]
@mckennapsean I've `done` options 1 & 2 (_updated the script in the google sheet and granted you edit access so you can perform future updates!_)

**Pull request merged**
