### PR TITLE
Removing honeypot field from submitted email

### PR DESCRIPTION
**Pull request by mhaddy**
PR for issue (enhancement) #176 to remove the "honeypot" field from the submitted email.

### CODE REVIEW

**Comment by mckennapsean** [comment]
Hmmm, I was just reading through my comments on the original issue. It is a little odd to have this code in the main clientside JS if it is a "bonus" feature at the end of the repo.

This is one of the things that nags me about the code here. There are different versions based on where you are in the tutorial and how many of these extras you want to tack on.

It makes it a pain to maintain.

We have some of the honeypot code in the main clientside JS. But some of it is commented out. Oh boy.

Should these changes be added for all users of the form or just added in the readme for people using a honeypot? Or should we require the honeypot on all forms by default? The challenge is that this depends on what is put into the HTML, which we have no way of knowing.

Eventually, I wanted to add flags set as attributes on HTML elements, so that you could enable/disable things like a honeypot and not have to worry about commenting out stuff from the JS for something simple like this. Then people could have both worlds. I started implementing this with the variable-input email. This also has other security concerns. Giving people options opens up security holes (while also opening up possibilities).

**Comment by mhaddy** [comment]
@mckennapsean I've updated my commit (and other references in the file that I didn't modify) to use double quotes to maintain consistency. Re your other comments ... I think those are bigger builds - worth considering, but outside the scope of this PR.

**Comment by mckennapsean** [comment]
Thanks for adding in those fixes and elsewhere, much appreciated! I will plan to get this & the other PR merged & deployed over the weekend.

**Comment by mhaddy** [comment]
@mckennapsean, Shall I go ahead and delete the mhaddy:patch-1 branch and its equivalent for #195?

**Comment by mckennapsean** [comment]
You can, yup! You can even delete your fork of the repo if you want. You can verify the commits on master: https://github.com/dwyl/html-form-send-email-via-google-script-without-server/commits/master

**Comment by nelsonic** [comment]
@mckennapsean access granted:
https://www.npmjs.com/package/html-form-send-email-via-google-script-without-server/access
image
please confirm you can update. thanks.

**Comment by mckennapsean** [comment]
@nelsonic confirmed, I am listed as a collaborator! going to get a new major version published tonight! #123

**Pull request merged**
